language: node_js

nodejs:
  - 14

branches:
  only:
  - master

cache:
  directories:
    - "node_modules"
  yarn: true

notification:
  email: false

script:
  - yarn build
  - yarn test

after_success: yarn coveralls
