version: '3.8'
services:
  nest-api:
    container_name: nest-graphql-api-prod
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - postgres
    networks:
      - nest-graphql-network

  postgres:
    image: postgres:latest
    container_name: nest-postgres
    restart: always
    env_file:
      - .env.production
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nest-graphql-network
    logging:
      driver: none


  nest-nginx:
    container_name: nest-nginx
    restart: always
    build:
      context: docker/nginx
      dockerfile: Dockerfile.nginx
    depends_on:
      - nest-api
    ports:
      - 80:80
    env_file:
      - .env.nginx
    networks:
      - nest-graphql-network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - nestjs_network
    logging:
      driver: none

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
        - redis
    networks:
      - nestjs_network
    logging:
      driver: none


volumes:
  postgres_data:
    driver: local
networks:
  nest-graphql-network:
    driver: bridge
    name: nest-graphql-network
